on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      # Checkout source code
      - name: Checkout Repository 
        uses: actions/checkout@v1
      
      # Install proper ruby version
      - name: Install Ruby 3.1
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.1
          
      # Install gems
      - name: Install Ruby Gems
        working-directory: ./StormySky.iOS
        run: bundle install
    
      - name: Select XCode 14
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with: 
          xcode-version: '14.0.1'

      # Execute Unit Tests
      - name: Run Automated Tests
        working-directory: ./StormySky.iOS
        run: bundle exec fastlane test_ios
