on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      # Checkout source code
      - name: Checkout Repository 
        uses: actions/checkout@v1
      
      # Install proper ruby version
      - name: Install Ruby 3.1
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.1
      
      # Change directory to iOS Project Root
      - name: Switch to iOS Root Dir
        run: cd StormySky.iOS
      
      # Install gems
      - name: Install Ruby Gems
        run: bundle install
