on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-12
    steps:
      # Checkout source code
      - name: Checkout Repository 
        uses: actions/checkout@v1

      # Install proper ruby version
      - name: Install Ruby 3.1
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.1
          
      # Install gems
      - name: Install Ruby Gems
        working-directory: ./StormySky.iOS
        run: bundle install

      # Install Provisioning Profiles and Certificates using Fastlane Match
      - name: Install the Apple certificate and provisioning profile
        working-directory: ./StormySky.iOS
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          GIT_MATCH_TOKEN: ${{ secrets.GIT_MATCH_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane appstore_sync
      
      - name: Check Profiles
        run: ls -all ~/Library/MobileDevice/Provisioning

      # Execute Unit Tests
      # - name: Run Automated Tests
      #   working-directory: ./StormySky.iOS
      #   run: bundle exec fastlane test_ios

      - name: Build App Store IPA
        working-directory: ./StormySky.iOS
        run: bundle exec fastlane build_appstore
