on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-12
    steps:
      # Checkout source code
      - name: Checkout Repository 
        uses: actions/checkout@v1

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPSTORE_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.APPSTORE_CERTIFICATE_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPSTORE_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPSTORE_CERTIFICATE_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      
      - name: Check Profiles
        run: ls -all ~/Library/MobileDevice/Provisioning
      # Install proper ruby version
      - name: Install Ruby 3.1
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.1
          
      # Install gems
      - name: Install Ruby Gems
        working-directory: ./StormySky.iOS
        run: bundle install

      # Execute Unit Tests
      # - name: Run Automated Tests
      #   working-directory: ./StormySky.iOS
      #   run: bundle exec fastlane test_ios

      - name: Build App Store IPA
        working-directory: ./StormySky.iOS
        run: bundle exec fastlane build_appstore
